server {
    listen 3007;
    server_name localhost;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Enable client-side routing by serving index.html for all non-file routes
        try_files $uri $uri/ /index.html;
    }
}
