// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SystemManagementApp.Data;

#nullable disable

namespace SystemManagementApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240708101732_test1")]
    partial class test1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SystemManagementApp.Model.ActionBy", b =>
                {
                    b.Property<int>("actionById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("actionById"));

                    b.Property<string>("actionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("actionById");

                    b.ToTable("ActionBies");
                });

            modelBuilder.Entity("SystemManagementApp.Model.DeviceType", b =>
                {
                    b.Property<int>("deviceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("deviceTypeId"));

                    b.Property<string>("deviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("deviceTypeId");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("SystemManagementApp.Model.EventDescription", b =>
                {
                    b.Property<int>("eventDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("eventDescriptionId"));

                    b.Property<string>("eventDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("eventDescriptionId");

                    b.ToTable("EventDescription");
                });

            modelBuilder.Entity("SystemManagementApp.Model.EventType", b =>
                {
                    b.Property<int>("eventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("eventTypeId"));

                    b.Property<string>("eventTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("eventTypeId");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("SystemManagementApp.Model.Events", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("actionBy")
                        .HasColumnType("integer");

                    b.Property<string>("dateTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("deviceType")
                        .HasColumnType("integer");

                    b.Property<int>("eventDescription")
                        .HasColumnType("integer");

                    b.Property<int>("eventType")
                        .HasColumnType("integer");

                    b.Property<int>("eventid")
                        .HasColumnType("integer");

                    b.Property<int>("plantName")
                        .HasColumnType("integer");

                    b.Property<int>("priority")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("SystemManagementApp.Model.PlantName", b =>
                {
                    b.Property<int>("plantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("plantId"));

                    b.Property<string>("plantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("plantId");

                    b.ToTable("PlantName");
                });

            modelBuilder.Entity("SystemManagementApp.Model.Priority", b =>
                {
                    b.Property<int>("priorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("priorityId"));

                    b.Property<string>("priorityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("priorityId");

                    b.ToTable("Priorities");
                });
#pragma warning restore 612, 618
        }
    }
}
